style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Rmtram/Sorter
options:
  commits:
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE